services:
  type: web
  name: aimodel
  runtime: python
  plan: free
  autoDeploy: false
  buildCommand: pip install -r requirements.txt
  pythonVersion: 3.10.12
  startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT